servitium:
  butterfly:
    url-prefix: https://butterfly.servitiumcrm.com/butterfly/
  app:
    url-prefix: https://app.servitiumcrm.com/butterfly/
  jobsheets:
    enable-async: false

aws:
  s3:
    captcha-bucket: captcha-bucket
  ses:
    enabled: true

variables:
  button: MMXDDYMMZ771775776FFY336225WWXAAYCCZDDYJJYEEP226AAZIIYKKQAAL
  link: https://Y-DhD7u+7Lak-dcjj95@7NbmNng-SJZUnIl-XzxFE_sC21.com